name: Release
on: 
  workflow_call:
    secrets:
      token:
        required: true
    inputs:
      docker_image:
        required: true
        type: string
      docker_platforms:
        required: false
        default: linux/amd64,linux/arm64
        type: string

jobs:
  docker:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ inputs.docker_image }}
          tags: |
            type=ref,event=branch
            type=raw,value=latest

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ inputs.docker_platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha
          cache-from: type=gha

  version:
    name: Semantic release
    needs: docker
    runs-on: ubuntu-latest
    outputs:
      new_release_published: "${{ steps.semantic.outputs.new_release_published }}"
      new_release_version: "${{ steps.semantic.outputs.new_release_version }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic
        with:
          extra_plugins: |
            'https://gitpkg.now.sh/stenic/github-workflows/semantic-release/docker-helm?v0.1.0'
            github:NoUseFreak/semantic-release-helm#v2.2.0-alpha.1
          extends: |
            https://gitpkg.now.sh/stenic/github-workflows/semantic-release/docker-helm?v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}

  docker_release:
    name: Docker release
    needs: version
    if: ${{ needs.version.outputs.new_release_published == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Current
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ${{ inputs.docker_image }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}},value=${{ needs.version.outputs.new_release_version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.version.outputs.new_release_version }}
            type=semver,pattern={{major}},value=${{ needs.version.outputs.new_release_version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.token }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ inputs.docker_platforms }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
